package com.zhoudu.dao;

import com.zhoudu.domain.GoodsPackage;
import com.zhoudu.domain.GoodsPackageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsPackageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_package
     *
     * @mbg.generated Sat Oct 23 18:42:50 GMT+08:00 2021
     */
    long countByExample(GoodsPackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_package
     *
     * @mbg.generated Sat Oct 23 18:42:50 GMT+08:00 2021
     */
    int deleteByExample(GoodsPackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_package
     *
     * @mbg.generated Sat Oct 23 18:42:50 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_package
     *
     * @mbg.generated Sat Oct 23 18:42:50 GMT+08:00 2021
     */
    int insert(GoodsPackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_package
     *
     * @mbg.generated Sat Oct 23 18:42:50 GMT+08:00 2021
     */
    int insertSelective(GoodsPackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_package
     *
     * @mbg.generated Sat Oct 23 18:42:50 GMT+08:00 2021
     */
    List<GoodsPackage> selectByExample(GoodsPackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_package
     *
     * @mbg.generated Sat Oct 23 18:42:50 GMT+08:00 2021
     */
    GoodsPackage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_package
     *
     * @mbg.generated Sat Oct 23 18:42:50 GMT+08:00 2021
     */
    int updateByExampleSelective(@Param("record") GoodsPackage record, @Param("example") GoodsPackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_package
     *
     * @mbg.generated Sat Oct 23 18:42:50 GMT+08:00 2021
     */
    int updateByExample(@Param("record") GoodsPackage record, @Param("example") GoodsPackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_package
     *
     * @mbg.generated Sat Oct 23 18:42:50 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(GoodsPackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_package
     *
     * @mbg.generated Sat Oct 23 18:42:50 GMT+08:00 2021
     */
    int updateByPrimaryKey(GoodsPackage record);
}