package com.zhoudu.dao;

import com.zhoudu.domain.GoodsConfigure;
import com.zhoudu.domain.GoodsConfigureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsConfigureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_configure
     *
     * @mbg.generated Sat Oct 23 18:42:50 GMT+08:00 2021
     */
    long countByExample(GoodsConfigureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_configure
     *
     * @mbg.generated Sat Oct 23 18:42:50 GMT+08:00 2021
     */
    int deleteByExample(GoodsConfigureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_configure
     *
     * @mbg.generated Sat Oct 23 18:42:50 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_configure
     *
     * @mbg.generated Sat Oct 23 18:42:50 GMT+08:00 2021
     */
    int insert(GoodsConfigure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_configure
     *
     * @mbg.generated Sat Oct 23 18:42:50 GMT+08:00 2021
     */
    int insertSelective(GoodsConfigure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_configure
     *
     * @mbg.generated Sat Oct 23 18:42:50 GMT+08:00 2021
     */
    List<GoodsConfigure> selectByExample(GoodsConfigureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_configure
     *
     * @mbg.generated Sat Oct 23 18:42:50 GMT+08:00 2021
     */
    GoodsConfigure selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_configure
     *
     * @mbg.generated Sat Oct 23 18:42:50 GMT+08:00 2021
     */
    int updateByExampleSelective(@Param("record") GoodsConfigure record, @Param("example") GoodsConfigureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_configure
     *
     * @mbg.generated Sat Oct 23 18:42:50 GMT+08:00 2021
     */
    int updateByExample(@Param("record") GoodsConfigure record, @Param("example") GoodsConfigureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_configure
     *
     * @mbg.generated Sat Oct 23 18:42:50 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(GoodsConfigure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_configure
     *
     * @mbg.generated Sat Oct 23 18:42:50 GMT+08:00 2021
     */
    int updateByPrimaryKey(GoodsConfigure record);
}